"""initial schema

Revision ID: 735f7eaf3857
Revises: 
Create Date: 2026-08-31 15:02:05.494320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735f7eaf3857'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor', sa.String(length=60), nullable=False),
    sa.Column('os', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_devices_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_devices_organization_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_key', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('secret_hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_configurations_device_id_devices')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_configurations_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations')),
    sa.UniqueConstraint('device_id', 'sha256', name=op.f('uq_configurations_device_id'))
    )
    op.create_index(op.f('ix_configurations_sha256'), 'configurations', ['sha256'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('audit_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=40), nullable=False),
    sa.Column('framework_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rule_pack_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('detected_vendor', sa.String(length=60), nullable=True),
    sa.Column('detected_os', sa.String(length=60), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('detection_reasons', sa.JSON(), nullable=False),
    sa.Column('vendor_override', sa.String(length=60), nullable=True),
    sa.Column('unknown_constructs', sa.JSON(), nullable=False),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_audit_runs_configuration_id_configurations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_runs'))
    )
    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('framework', sa.String(length=40), nullable=False),
    sa.Column('framework_version', sa.String(length=40), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evidence_lines', sa.JSON(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_compliance_results_audit_run_id_audit_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    op.create_index(op.f('ix_compliance_results_rule_id'), 'compliance_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_severity'), 'compliance_results', ['severity'], unique=False)
    op.create_index(op.f('ix_compliance_results_status'), 'compliance_results', ['status'], unique=False)
    op.create_table('normalized_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('source_lines', sa.JSON(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('parser_confidence', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_normalized_controls_audit_run_id_audit_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_controls'))
    )
    op.create_index(op.f('ix_normalized_controls_key'), 'normalized_controls', ['key'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column('blob_key', sa.String(length=255), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_reports_audit_run_id_audit_runs')),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compliance_result_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('remediation_id', sa.String(length=60), nullable=False),
    sa.Column('triage_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_result_id'], ['compliance_results.id'], name=op.f('fk_findings_compliance_result_id_compliance_results')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('reports')
    op.drop_index(op.f('ix_normalized_controls_key'), table_name='normalized_controls')
    op.drop_table('normalized_controls')
    op.drop_index(op.f('ix_compliance_results_status'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_severity'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_rule_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_configurations_sha256'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('devices')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
