"""add ai interpretations

Revision ID: 7707662d0c81
Revises: 735f7eaf3857
Create Date: 2026-09-02 20:03:37.514583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7707662d0c81'
down_revision: Union[str, Sequence[str], None] = '735f7eaf3857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column('construct_index', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('suggested_parameter', sa.String(length=120), nullable=True),
    sa.Column('suggested_value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_ai_interpretations_audit_run_id_audit_runs')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_ai_interpretations_reviewed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_interpretations')),
    sa.UniqueConstraint('audit_run_id', 'construct_index', name=op.f('uq_ai_interpretations_audit_run_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_interpretations')
    # ### end Alembic commands ###
